/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adat_proyecto_json_wendel;
import adat_proyecto_json_wendel.gestion.gestionJSON.ConcellosManager;
import adat_proyecto_json_wendel.gestion.gestionJSON.DescripcionParser;
import adat_proyecto_json_wendel.gestion.gestionJSON.GestionPrediccion;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // Rutas ficheros con datos JSON, ruta común
        String rutaPaqueteGestionJSON = "app/src/main/java/adat_proyecto_json_wendel/gestion/gestionJSON/dataJson/";
        // Nombre fichero Json con valores de las descripciones
        String rutaDescripcionesPredicciones = rutaPaqueteGestionJSON + "descripciones.json";
        // Nombre fichero Json con la lista de id de los concellos
        String rutaListaIdConcellos = rutaPaqueteGestionJSON + "listaIdConcellos.json";


        // Instanciar el parser con la ruta del JSON de las descripciones
        DescripcionParser descripcionParser = new DescripcionParser(rutaDescripcionesPredicciones); 

        // Parser para obtener los id de los concellos
        ConcellosManager manager = new ConcellosManager(rutaListaIdConcellos);
        
        // Leer datos de un Concello
        //obtenerIdConcelloPorNombre(manager,"Baleira");

        // Instanciar la clase de GestionPrediccion
        GestionPrediccion gestion = new GestionPrediccion(descripcionParser);

        /* 
        String urlCoruna = "https://servizos.meteogalicia.gal/mgrss/predicion/jsonPredConcellos.action?idConc=15030&request_locale=gl";
        PrediccionConcello prediccionCoruna = gestion.obtenerPrediccion(urlCoruna);

        String urlOurense = "https://servizos.meteogalicia.gal/mgrss/predicion/jsonPredConcellos.action?idConc=32054&request_locale=gl";
        PrediccionConcello prediccionOurense = gestion.obtenerPrediccion(urlOurense);

        if (prediccionCoruna != null) {
            System.out.println(prediccionCoruna.getNome());

            System.out.println(prediccionOurense.getNome());
            //gestion.mostrarDatosPrediccion(prediccion);

            // Nombre fichero para guardar el CSV
            String nombreArchivo = "25-11-2023-galicia.csv";

            // Obtener datos de la predicción en formato CSV
            List<String[]> datos = CSVWriterExample.getDatosPrediccionesEnCSV(List.of(prediccionCoruna,prediccionOurense), descripcionParser); // Reemplaza esto con tus propios datos
            //List<String[]> datos = CSVWriterExample.obtenerDatosConcello(prediccion);

            CSVWriterExample.crearCSV(nombreArchivo, datos);

        } else {
            System.out.println("La prediccion es null.");
        }

        */

    }

    public static void obtenerIdConcelloPorNombre(ConcellosManager manager, String nombreConcello){

        int idConcello = manager.obtenerIdConcelloPorNombre(nombreConcello);

        if (idConcello != -1) {
            System.out.println("El ID del concello '" + nombreConcello + "' es: " + idConcello);
        } else {
            System.out.println("No se encontró el concello '" + nombreConcello + "'.");
        }
    }
}
